---
title: "Adding Interactivity to Static Rmarkdown Documents"
author: ~
date: "`r Sys.time()`"
day: "`r format(Sys.Date(), '%d')`"
month: "`r format(Sys.Date(), '%b')`"
year: "`r format(Sys.Date(), '%Y')`"
slug: adding-rmarkdown-interactivity
categories: []
tags: ["R", "R Markdown", "Javascript", "Highcharts"]
highlight: "kate"
description: "Interactivity can be added to static HTML R Markdown outputs by using a couple of cool tricks."
img: "bulletin-edition-1"
---


# Generate Data

```{r}
library(dplyr)
library(tidyr)

data <- data.frame(
  normal = rnorm(10000, 5, 2), # 1000 random from normal dist
  exponential = rexp(10000, 0.5), # 1000 random from exponential dist
  uniform = runif(10000, 0, 10) # 1000 random from uniform dist
)

# Data Manipulation
data %>%
  gather(distribution, value, normal:uniform) %>%
  mutate(value = value %>% round(1)) %>%
  filter(value >= 0, value <= 12) %>%
  group_by(distribution, value) %>%
  summarise(points = n()) %>%
  ungroup() %>% group_by(distribution) %>%
  mutate(density = points / sum(points)) %>%
  ungroup() %>%
  select(-points) -> density

```


# Plot Data

```{r}

library(highcharter)


plot_data = density %>% spread(distribution, density)

  highchart() %>%
  hc_add_theme(hc_theme_monokai()) %>%
  hc_chart(
    animation = list(duration = 2000),
    height = 500
  ) %>%
  hc_xAxis(
    categories = plot_data$value,
    title = list(text = "Value")
  ) %>%
  hc_yAxis(
    title = list(text = "Probablity Density"),
    labels = list(formatter = JS("function(){return(Math.round(this.value * 1000) / 10 + '%')}"))
  ) %>%
  hc_title(text = "3 Probability Densities") %>%
  hc_add_series(
    name = "Normal", 
    type = "spline",
    data = plot_data$normal,
    marker = list(enabled = FALSE)
  ) %>%
  hc_add_series(
    name = "Exponential",
    type = "spline",
    data = plot_data$exponential,
    marker = list(enabled = FALSE)
  ) %>%
  hc_add_series(
    name = "Uniform",
    type = "spline",
    data = plot_data$uniform,
    marker = list(enabled = FALSE)
  )


```



# Add Interactivity


```{class.source="language-javascript"}

$(document).ready(function() {

  var show_cdf = false;
  
  $("#update_age_series").click(function(){
  
    var chart=$("#age_series_chart").find(".highchart").highcharts();
    
    if (show_cdf) {
    
      chart.yAxis[0].setExtremes(0,null);
      chart.yAxis[0].setTitle({text:"Probability Density", redraw:false});
      #dir_pdf = `r dir_pdf`;
      #female_pdf = `r female_pdf`;
      #male_pdf = `r male_pdf`;
      chart.series[0].setData(dir_pdf);
      chart.series[1].setData(male_pdf);
      chart.series[2].setData(female_pdf);
      $("#update_age_series").html("Show Cumulative Distribution");
    
    } else {
    
      chart.yAxis[0].setExtremes(0,1);
      chart.yAxis[0].setTitle({text:"Cumulative Probability", redraw:false});
      #dir_cdf = `r dir_cdf`;
      #female_cdf = `r female_cdf`;
      #male_cdf = `r male_cdf`;
      chart.series[0].setData(dir_cdf);
      chart.series[1].setData(male_cdf);
      chart.series[2].setData(female_cdf);
      
      $("#update_age_series").html("Show Density");
    
  };
  
  show_cdf = !show_cdf
  
  }); 
});

```
